apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: monitoring
  labels: 
    app: prometheus
spec:
  type: LoadBalancer 
  selector:
    app: prometheus
  ports:
    - port: 80
      targetPort: 9090
      protocol: TCP

